config/routes.rb
Rails.application.routes.draw do
  get "articles", to: "articles#index"


  get "articles/new", to: "articles#new", as: :new_article
  post "articles", to: "articles#create"

  get "articles/:id", to: "articles#show", as: :article

  get "articles/:id/edit", to: "articles#edit", as: :edit_article
  patch "articles/:id", to: "articles#update"

  delete "articles/:id", to: "articles#destroy", as: :delete_article

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  def article_params
    params.require(:article).permit(:title, :content, :created_at)
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <p><%= f.label :title %></p>
  <%= f.text_field :title %>


  <p><%= f.label :content %></p>
  <%= f.text_area :content, size: "200x20" %>

  <p><%= f.submit %></p>
<% end %>

app/views/articles/edit.html.erb
<h1> Edit your article </h1>

<%=render 'form' %>

app/views/articles/index.html.erb
<h1>Your Articles</h1>
<h2>Total number of articles: <%= @articles.count %></h2>
<button><%= link_to "Add a new article", new_article_path %></button>

<ol>
  <% @articles.each do |article| %>
    <li><strong><%= link_to article.title, article_path(article) %></strong>
      <p> <%= article.content %> </p>
    </li>
  <% end %>
</ol>

app/views/articles/new.html.erb
<h1>Create a new article</h1>


<%=render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<hr>
<h2><%= @article.created_at %></h2>
<hr>
<%= sanitize Kramdown::Document.new(@article.content).to_html %>

<hr>
<button><%= link_to "Edit this article", edit_article_path(@article) %></button>
<button><%= link_to "Back to all articles", articles_path %></button>

<button><%= link_to "Delete this artcile", delete_article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>